# The database of schools
# The data is of 2021
school_db = [
    #School name
    #location
    #year founded
    # undergrad class size
    # acceptance rate
    (
        "Harvard University",
        "Cambridge, Massachusetts, USA",
        1636,
        6700,
        4.6,
    ),
    (
        "Yale University",
        "New Haven, Connecticut, USA",
        1701,
        5900,
        6.6,
    ),
    (
        "Princeton University",
        "Princeton, New Jersey, USA",
        1746,
        5200,
        5.5,
    ),
    (
        "Columbia University",
        "New York City, New York, USA",
        1754,
        8200,
        5.3,
    ),
    (
        "University of Pennsylvania",
        "Philadelphia, Pennsylvania, USA",
        1740,
        10,400,
        7.7,
    ),
    (
        "Brown University",
        "Providence, Rhode Island, USA",
        1764,
        6700,
        7.1,
    ),
    (
        "Dartmouth College",
        "Hanover, New Hampshire, USA",
        1769,
        4500,
        9.2,
    ),
    (
        "Cornell University",
        "Ithaca, New York, USA",
        1865,
        15,100,
        10.9,
    ),
    # Additional Schools
    (
        "Massachusetts Institute of Technology (MIT)",
        "Cambridge, Massachusetts, USA",
        1861,
        4600,
        6.7,
    ),
    (
        "Stanford University",
        "Stanford, California, USA",
        1885,
        7200,
        4.3,
    ),
    (
        "University of Chicago",
        "Chicago, Illinois, USA",
        1890,
        6000,
        6.2,
    ),
    (
        "University of California, Berkeley",
        "Berkeley, California, USA",
        1868,
        30,800,
        16.9,
    ),
    (
        "University of Michigan",
        "Ann Arbor, Michigan, USA",
        1817,
        31,300,
        22.3,
    ),
    # Additional Schools (12 more for a total of 20)
    (
        "University of Texas at Austin",
        "Austin, Texas, USA",
        1883,
        40,000,
        32.2,
    ),
    (
        "University of Florida",
        "Gainesville, Florida, USA",
        1853,
        35,000,
        37.0,
    ),
    (
        "University of Washington",
        "Seattle, Washington, USA",
        1861,
        32,000,
        52.3,
    ),
    (
        "University of California, Los Angeles (UCLA)",
        "Los Angeles, California, USA",
        1919,
        45,000,
        12.4,
    ),
    (
        "University of North Carolina at Chapel Hill",
        "Chapel Hill, North Carolina, USA",
        1789,
        29,000,
        21.3,
    ),
    (
        "University of Virginia",
        "Charlottesville, Virginia, USA",
        1819,
        16,500,
        24.6,
    ),
    (
        "University of Wisconsin-Madison",
        "Madison, Wisconsin, USA",
        1848,
        31,000,
        54.3,
    ),
    (
        "University of California, San Diego (UCSD)",
        "La Jolla, California, USA",
        1960,
        30,000,
        30.2,
    ),
    (
        "University of California, Davis (UC Davis)",
        "Davis, California, USA",
        1905,
        30,900,
        41.3,
    ),
    (
        "University of Maryland, Baltimore County (UMBC)",
        "Baltimore, Maryland, USA",
        1966,
        14,000,
        58.6,
    ),
    (
        "University of Oregon",
        "Eugene, Oregon, USA",
        1876,
        22,300,
        83.8,
    ),
    (
        "Indiana University Bloomington",
        "Bloomington, Indiana, USA",
        1820,
        32,500,
        77.8,
    ),
    (
        "University of Iowa",
        "Iowa City, Iowa, USA",
        1847,
        24,500,
        83.2,
    ),
    (
        "University of Kansas",
        "Lawrence, Kansas, USA",
        1865,
        19,500,
        92.0,
    ),
    (
        "University of Kentucky",
        "Lexington, Kentucky, USA",
        1865,
        22,200,
        93.5,
    ),
    (
        "University of New Mexico",
        "Albuquerque, New Mexico, USA",
        1889,
        19,400,
        91.3,
    ),
    (
        "University of Oklahoma",
        "Norman, Oklahoma, USA",
        1890,
        22,000,
        77.3,
    ),
    (
        "University of South Carolina",
        "Columbia, South Carolina, USA",
        1801,
        26,400,
        68.6,
    ),
    (
        "University of Tennessee, Knoxville",
        "Knoxville, Tennessee, USA",
        1794,
        22,500,
        77.0,
    ),
    (
        "University of Utah",
        "Salt Lake City, Utah, USA",
        1850,
        24,600,
        66.5,
    ),
    (
        "University of Vermont",
        "Burlington, Vermont, USA",
        1791,
        11,000,
        66.7,
    ),
    (
        "University of Wyoming",
        "Laramie, Wyoming, USA",
        1886,
        9,000,
        96.4,
    ),
    (
        "Auburn University",
        "Auburn, Alabama, USA",
        1856,
        24,600,
        84.3,
    ),
    (
        "Boise State University",
        "Boise, Idaho, USA",
        1932,
        19,200,
        81.8,
    ),
    (
        "University of Arkansas",
        "Fayetteville, Arkansas, USA",
        1871,
        22,500,
        77.3,
    ),
    (
        "Louisiana State University (LSU)",
        "Baton Rouge, Louisiana, USA",
        1860,
        26,100,
        73.8,
    ),
    (
        "University of Nevada, Las Vegas (UNLV)",
        "Las Vegas, Nevada, USA",
        1957,
        25,000,
        83.4,
    ),
    (
        "University of Mississippi (Ole Miss)",
        "Oxford, Mississippi, USA",
        1848,
        17,000,
        88.6,
    ),
]
